USE sakila;

#List the number of films per category.

SELECT c.name AS category, COUNT(fc.film_id) AS number_of_films
FROM category  AS c
INNER JOIN film_category AS fc 
ON c.category_id = fc.category_id
GROUP BY c.name;

#Retrieve the store ID, city, and country for each store.
SELECT store_id, city, country
FROM store  
INNER JOIN address
USING(address_id)
INNER JOIN city
USING(city_id)
INNER JOIN country
USING(country_id);



#Calculate the total revenue generated by each store in dollars.

SELECT s.store_id, SUM(p.amount) AS total_revenue
FROM store AS s
INNER JOIN staff AS st ON s.store_id = st.store_id
INNER JOIN payment AS p ON st.staff_id = p.staff_id
GROUP BY s.store_id;


#Determine the average running time of films for each category.
SELECT c.name AS category, AVG(f.length) AS average_running_time
FROM category AS c
INNER JOIN film_category AS fc ON c.category_id = fc.category_id
INNER JOIN film AS f ON fc.film_id = f.film_id
GROUP BY c.name;
